// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table usuarios {
  id integer [pk]
  nome_completo varchar
  email varchar [unique]
  senha_hash varchar
  tipo_documento varchar [note: 'CPF ou CNPJ']
  documento varchar [unique]
  saldo_moedas numeric [default: 0.00]
  data_cadastro timestamp
  endereco jsonb [note: 'Endereço completo em formato JSON']
}

Table tipos_de_material {
  id integer [pk]
  nome varchar [unique]
  valor_por_kg numeric
}

Table pacotes_de_residuos {
  id integer [pk]
  id_ponto_descarte integer [not null]
  id_ponto_coleta integer
  id_ponto_destino integer
  status varchar [note: 'disponivel, em_transporte, concluido']
  valor_pacote_moedas numeric [note: 'Valor definido pelo Ponto de Descarte']
  valor_coleta_moedas numeric [note: 'Valor de transporte definido pelo Ponto de Coleta, pode ser 0']
  id_material integer [not null, note: 'Tipo de material do pacote']
  peso_kg numeric [not null]
  data_criacao timestamp
  data_coleta timestamp
  data_destino timestamp
  localizacao jsonb [note: 'Coordenadas geográficas do pacote']
}

Table mensagens_pacote {
  id integer [pk]
  id_pacote integer
  id_remetente integer
  mensagem text
  data_envio timestamp
}

Table itens_da_loja {
  id integer [pk]
  id_vendedor integer
  nome_item varchar
  descricao text
  valor_moedas numeric
  tipo_item varchar [note: 'produto, servico, cupom']
  disponibilidade integer
}

Table transacoes_de_moedas {
  id integer [pk]
  id_origem integer [note: 'ID do usuário que está pagando, ou nulo se for compra/venda na plataforma']
  id_destino integer [note: 'ID do usuário que está recebendo']
  valor numeric
  tipo varchar [note: 'destinacao, coleta, compra_reais, venda_loja, aquisicao, solicitacao_coleta, compra_loja']
  id_referencia integer [note: 'ID do pacote ou do item da loja']
  data_transacao timestamp
}

// Relacionamentos
Ref: pacotes_de_residuos.id_ponto_descarte > usuarios.id
Ref: pacotes_de_residuos.id_ponto_coleta > usuarios.id
Ref: pacotes_de_residuos.id_ponto_destino > usuarios.id

Ref: pacotes_de_residuos.id_material > tipos_de_material.id

Ref: mensagens_pacote.id_pacote > pacotes_de_residuos.id
Ref: mensagens_pacote.id_remetente > usuarios.id

Ref: itens_da_loja.id_vendedor > usuarios.id

Ref: transacoes_de_moedas.id_origem > usuarios.id
Ref: transacoes_de_moedas.id_destino > usuarios.id